from app.crm.schemas.analytics import (
    AnalyticsCategoryOrdersRead,
    AnalyticsCategoryRead,
    AnalyticsFilterEchoRead,
    AnalyticsOverviewRead,
    AnalyticsServiceBreakdownRead,
)
from app.crm.schemas.auth import CurrentUserRead, LoginRequest, RefreshRequest, ResetPasswordRequest, TokenPairRead
from app.crm.schemas.client import ClientCreate, ClientRead
from app.crm.schemas.document import DocumentFileRead, DocumentPreviewRead, DocumentPrintRead, DocumentRead, DocumentTemplateRead
from app.crm.schemas.inspection import (
    InspectionActGenerateRead,
    InspectionExportPreviewRead,
    InspectionExportRead,
    InspectionGeneralPhotoRead,
    InspectionHistoryRead,
    InspectionMarkCreatePayload,
    InspectionMarkPhotoRead,
    InspectionMarkRead,
    InspectionMarkReorderPayload,
    InspectionMarkUpdatePayload,
    InspectionSessionDetailRead,
    InspectionSessionPatch,
    InspectionSessionRead,
)
from app.crm.schemas.order import (
    OrderCreate,
    OrderRead,
    OrderServiceCreate,
    OrderStatusUpdate,
    OrderSummaryRead,
)
from app.crm.schemas.reminder import (
    NotificationRead,
    ReminderCreate,
    ReminderDoneUpdate,
    ReminderPostponeUpdate,
    ReminderRead,
    ReminderRepeatUpdate,
    ReminderTargetSummaryRead,
)
from app.crm.schemas.reference_catalog import CarBrandCreate, CarBrandRead, CarModelCreate, CarModelRead
from app.crm.schemas.material import MaterialCreate, MaterialRead
from app.crm.schemas.material_attachment import MaterialAttachmentRead
from app.crm.schemas.finance_expense_attachment import FinanceExpenseAttachmentRead
from app.crm.schemas.service_catalog import ServiceCatalogCreate, ServiceCatalogRead
from app.crm.schemas.service_category import ServiceCategoryCreate, ServiceCategoryRead
from app.crm.schemas.settings import SettingsRead
from app.crm.schemas.summary import (
    ClientDetailRead,
    ClientSummaryRead,
    OrderHistoryRead,
    ServiceFrequencyRead,
    ServiceHistoryEntryRead,
    ServiceHistoryRead,
    VehicleDetailRead,
    VehicleOwnerHistoryRead,
    VehicleSummaryRead,
)
from app.crm.schemas.user import RoleCreate, RoleRead, UserCreate, UserPasswordReset, UserRead, UserStatusUpdate, UserUpdate
from app.crm.schemas.vehicle import VehicleCreate, VehicleOwnerChangeCreate, VehicleRead

__all__ = [
    "AnalyticsCategoryOrdersRead",
    "AnalyticsCategoryRead",
    "AnalyticsFilterEchoRead",
    "AnalyticsOverviewRead",
    "AnalyticsServiceBreakdownRead",
    "CarBrandCreate",
    "CarBrandRead",
    "CarModelCreate",
    "CarModelRead",
    "ClientSummaryRead",
    "ClientDetailRead",
    "ClientCreate",
    "ClientRead",
    "MaterialCreate",
    "MaterialRead",
    "MaterialAttachmentRead",
    "FinanceExpenseAttachmentRead",
    "CurrentUserRead",
    "DocumentFileRead",
    "InspectionActGenerateRead",
    "InspectionExportPreviewRead",
    "InspectionExportRead",
    "InspectionGeneralPhotoRead",
    "InspectionHistoryRead",
    "InspectionMarkCreatePayload",
    "InspectionMarkPhotoRead",
    "InspectionMarkRead",
    "InspectionMarkReorderPayload",
    "InspectionMarkUpdatePayload",
    "InspectionSessionDetailRead",
    "InspectionSessionPatch",
    "InspectionSessionRead",
    "DocumentPreviewRead",
    "DocumentPrintRead",
    "DocumentRead",
    "DocumentTemplateRead",
    "LoginRequest",
    "NotificationRead",
    "OrderCreate",
    "OrderRead",
    "OrderHistoryRead",
    "OrderServiceCreate",
    "OrderStatusUpdate",
    "OrderSummaryRead",
    "RefreshRequest",
    "ReminderCreate",
    "ReminderDoneUpdate",
    "ReminderPostponeUpdate",
    "ReminderRead",
    "ReminderRepeatUpdate",
    "ReminderTargetSummaryRead",
    "ResetPasswordRequest",
    "RoleCreate",
    "RoleRead",
    "ServiceCatalogCreate",
    "ServiceCatalogRead",
    "ServiceCategoryCreate",
    "ServiceCategoryRead",
    "ServiceFrequencyRead",
    "ServiceHistoryEntryRead",
    "ServiceHistoryRead",
    "SettingsRead",
    "TokenPairRead",
    "UserCreate",
    "UserPasswordReset",
    "UserRead",
    "UserStatusUpdate",
    "UserUpdate",
    "VehicleCreate",
    "VehicleOwnerChangeCreate",
    "VehicleRead",
    "VehicleSummaryRead",
    "VehicleDetailRead",
    "VehicleOwnerHistoryRead",
]
